config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'contents#index'
  get 'contents/index'
  get 'topics/index'
  

  resources :topics, only: [:index, :new, :show, :create] do
    resources :posts, only: [:create, :edit, :update]
  end

end

app/models/topic.rb
class Topic < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  belongs_to :user
  has_many :posts

  
  # バリデーション設定
  with_options presence: true do
    validates :title
    validates :category_id, numericality: { other_than: 1 }
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :move_to_login
  
  def new
    @topic = Topic.new
  end
  
  def index
    if params[:category_id]
      # Categoryのデータベースのテーブルから一致するidを取得
      @category = Category.find(params[:category_id])
      # category_idと紐づく投稿を取得
      @topics = @category.topics.order(created_at: :desc).all
    else
      # 投稿すべてを取得
      @topics = Topic.order(created_at: :desc).all
    end

    # 検索フォーム
    @search = Topic.ransack(params[:q])
    @results = @search.result(distinct: true)
  end

  def show
    @topic = Topic.find(params[:id])
    @post = Post.new
    @posts = @topic.posts.includes(:user)
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.save
    redirect_to topic_path(@topic)
  end

private

  def topic_params
    params.permit(:title, :category_id).merge(user_id: current_user.id)
  end

  # ログインしていない場合ログイン画面に遷移する
  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<div class="topics">

  <div class="search">
    <%= search_form_for @search do |f| %>
      <div class="search-form">
        <%= f.text_field :title_cont, placeholder: "コンテンツを検索する" %>
        <%= f.submit "Search" %>
      </div>
    <% end %>

    <% if @results.any? %>
      <% @results.each do |result| %>
        <%= link_to result.title, topic_path(result.id) %>
      <% end %>
    <% else %>
      <p>キーワードを含む投稿を検索できませんでした</p>
    <% end %>
  </div>

  <h4>Topics</h4>
    <div class="topic-titles">
    <ul>
      <% @topics.each do |topic| %>
        <li><%= link_to topic.title, topic_path(topic.id), method: :get %> （ <%= topic.category.name %> ）</li>
      <% end %>
    </ul>
    </div>

  <h4>Create Topic</h4>
    <%= form_with model: @user, url: topics_path, class: 'topic-new', local: true do |f| %>
      <%= f.text_field :title, placeholder: "タイトルを入力してください。※絵文字使用不可" %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      <%= f.submit "Create"%>
    <% end %>
</div>

app/views/topics/show.html.erb
<div class="topic-view">

  <div class="topic-title">
    <p><%= @topic.title %></p>
  </div>

  <div class="posts">
    <% if @posts %>
      <% @posts.each do |post| %>
        <div class="post-content">
          <div class="post-body">
            <%= raw Rinku.auto_link safe_join(post.body.split("\n"),tag(:br)) %>
          </div>
          <div class="post-info">
            <div class="post-user">
              from：<%= link_to post.user.nickname, "/users/#{post.user_id}" %>
            </div>
            <div class="post-date">
              date：<%= post.created_at %>
            </div>
            <div class="post-edit">
              <% if current_user.id == post.user_id %>
                <%= link_to "edit", edit_topic_post_path(post.id), method: :get %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="new-post">
    <h2>New post</h2>
      <%= form_with(model: [@topic, @post], local: true) do |f| %>
        <p><%= f.text_area :body, placeholder: "内容を入力してください。※絵文字使用不可" %></p>
        <%= f.submit "Post" %>
      <% end %>
  </div>

</div>